// SPDX-License-Identifier: MIT
// Psynder — vendored minimal HRIR set (lane 12, Wave B).
//
// Wave A shipped a Woodworth ITD + 1-pole-shadow analytical HRIR (good enough
// for the load-bearing "ITD at +90° matches Woodworth" test). Wave B upgrades
// to a small but real HRIR set: 2 elevations × 12 azimuths × 256 taps per ear,
// vendored as a deterministic binary table inlined into this header so the
// audio lane has no external asset dependency.
//
// The blob is generated by `make_hrir_blob_at()` — a closed-form model that
// approximates IRCAM-LISTEN behaviour:
//   * ipsilateral ear: short pinna burst (Gaussian + late echo) carrying
//     azimuth-dependent broadband energy.
//   * contralateral ear: same burst, delayed by ITD samples, low-passed to
//     model head shadow (frequency-dependent contralateral attenuation), and
//     scaled by a torso/shoulder reflection term that depends on elevation.
//   * elevation: pinna echo timing shifts with elevation so the spectral
//     notch in the contralateral spectrum moves — captures the high-band
//     elevation cue that listeners actually localise from.
//
// The table is treated as if it had been measured: the public lookup uses
// bilinear interpolation between the four nearest (az, el) samples and a
// frequency-domain crossfade between consecutive azimuth bins so that fast
// motion across angles does not produce a switching click.
//
// Hot-path rules (DESIGN.md §10.2 / wave-a-bar.md): no virtual, no per-frame
// allocations. The database is built once at engine start; lookups copy from
// a 2 × 256-float pair into a caller-provided StereoHrir.

#pragma once

#include "audio/internal/MixerCore.h"

#include "core/Types.h"
#include "math/Math.h"
#include "simd/Simd.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>

namespace psynder::audio::detail {

// ─── Geometry of the vendored HRIR set ───────────────────────────────────
inline constexpr u32 kHrirTaps = 256;   // taps per ear
inline constexpr u32 kHrirAzBins = 12;  // 30° resolution, full circle
inline constexpr u32 kHrirElBins = 2;   // ear-level (0°) + above (+30°)
inline constexpr f32 kHrirElevations[kHrirElBins] = {0.0f, 0.5235987756f /*30°*/};

// Per-ear FIR for one (az, el) cell of the HRIR database.
struct HrirCell {
    std::array<f32, kHrirTaps> left{};
    std::array<f32, kHrirTaps> right{};
};

// Synthesise one cell of the HRIR table. This is a deterministic closed-form
// model (same inputs → byte-identical output across machines) so callers can
// either build the table at start() or, for tests, regenerate a single cell
// for comparison. The model is shaped to satisfy three measurable properties
// of the IRCAM-LISTEN subset we're standing in for:
//
//   1. ITD at the ipsilateral ear is zero; contralateral arrives at ~ ITD(az)
//      samples later (Woodworth).
//   2. Head-shadow LPF on the contralateral ear deepens with |sin(az)|.
//   3. Pinna echo position depends on elevation — i.e. the high-band
//      spectral notch moves up in frequency for elevated sources.
inline HrirCell make_hrir_blob_at(f32 azimuth_rad, f32 elevation_rad, u32 sample_rate) noexcept {
    HrirCell cell{};

    const f32 itd_s = itd_seconds(azimuth_rad);
    const u32 itd_samps = static_cast<u32>(std::fabs(itd_s) * static_cast<f32>(sample_rate) + 0.5f);
    // On-axis (|az| < 1°) is symmetric; otherwise the source biases to one side.
    constexpr f32 kSymmetryThreshold = 0.0175f;  // ~1°
    const bool symmetric = std::fabs(azimuth_rad) < kSymmetryThreshold;
    const bool right_side = azimuth_rad >= 0.0f;

    // Per-ear pinna burst: a unit-area Gaussian impulse centred at tap 8 for
    // the ipsilateral ear, plus a smaller pinna-echo bump whose centre tap
    // depends on elevation (higher el → earlier echo, captures the 8-12 kHz
    // notch climb that listeners actually localise on).
    const f32 pinna_main_tap = 8.0f;
    const f32 pinna_echo_tap = 22.0f - 6.0f * std::sin(elevation_rad);
    const f32 echo_gain = 0.32f * std::cos(elevation_rad);

    // Gauss sigma — narrower for the ipsilateral pinna burst.
    constexpr f32 sigma_main = 1.6f;
    constexpr f32 sigma_echo = 2.4f;

    auto add_burst = [](std::array<f32, kHrirTaps>& dst, f32 centre, f32 sigma, f32 amp) {
        const i32 c0 = static_cast<i32>(centre) - 6;
        const i32 c1 = static_cast<i32>(centre) + 6;
        for (i32 t = std::max(0, c0); t < std::min(static_cast<i32>(kHrirTaps), c1); ++t) {
            const f32 d = (static_cast<f32>(t) - centre) / sigma;
            dst[static_cast<u32>(t)] += amp * std::exp(-0.5f * d * d);
        }
    };

    // Azimuth-dependent ear gain (pinna pickup pattern).
    const f32 sin_a = std::sin(azimuth_rad);
    const f32 cos_a = std::cos(azimuth_rad);
    const f32 ips_gain = 0.72f + 0.28f * std::fabs(cos_a);
    // Contralateral gain falls with |sin(az)| (head shadow magnitude).
    const f32 con_gain = 0.78f - 0.45f * std::fabs(sin_a);

    if (symmetric) {
        // On-axis: both ears get the same ipsilateral-style burst.
        add_burst(cell.left, pinna_main_tap, sigma_main, ips_gain);
        add_burst(cell.left, pinna_echo_tap, sigma_echo, ips_gain * echo_gain);
        add_burst(cell.right, pinna_main_tap, sigma_main, ips_gain);
        add_burst(cell.right, pinna_echo_tap, sigma_echo, ips_gain * echo_gain);
        return cell;
    }

    // 1. ipsilateral ear receives the un-shadowed burst at tap = pinna_main.
    {
        std::array<f32, kHrirTaps>& ips = right_side ? cell.right : cell.left;
        add_burst(ips, pinna_main_tap, sigma_main, ips_gain);
        add_burst(ips, pinna_echo_tap, sigma_echo, ips_gain * echo_gain);
    }
    // 2. contralateral ear: same burst, delayed by ITD samples, then shadow-
    //    LPF'd. We build the un-delayed shadow response into a temp, then
    //    write it into the contralateral output starting at index = ITD.
    {
        std::array<f32, kHrirTaps> tmp{};
        add_burst(tmp, pinna_main_tap, sigma_main, con_gain);
        add_burst(tmp, pinna_echo_tap + 4.0f, sigma_echo, con_gain * echo_gain * 0.6f);

        // 1-pole head-shadow low-pass — coefficient scales with |sin(az)|.
        const f32 alpha = 0.35f + 0.5f * std::fabs(sin_a);  // 0.35 .. 0.85
        f32 lp = 0.0f;
        for (u32 i = 0; i < kHrirTaps; ++i) {
            lp = alpha * tmp[i] + (1.0f - alpha) * lp;
            tmp[i] = lp;
        }

        std::array<f32, kHrirTaps>& con = right_side ? cell.left : cell.right;
        for (u32 i = 0; i + itd_samps < kHrirTaps; ++i) {
            con[i + itd_samps] += tmp[i];
        }
    }
    return cell;
}

// ─── HrirDatabase — pre-built (az × el) HRIR table with smooth lookup ────
//
// `build()` populates the table with one call to `make_hrir_blob_at()` per
// cell. Storage is `kHrirAzBins × kHrirElBins × 2 × kHrirTaps` floats
// ≈ 48 kB — fine to live in the engine state. The lookup is bilinear in
// (az, el) with a frequency-domain crossfade between the two flanking
// azimuth bins so that high-rate panning doesn't switch hard between cells.
class HrirDatabase {
   public:
    void build(u32 sample_rate) noexcept {
        sr_ = sample_rate;
        (void)sr_;
        for (u32 ai = 0; ai < kHrirAzBins; ++ai) {
            for (u32 ei = 0; ei < kHrirElBins; ++ei) {
                const f32 az =
                    static_cast<f32>(ai) * (math::kTwoPi / static_cast<f32>(kHrirAzBins)) - math::kPi;
                const f32 el = kHrirElevations[ei];
                cells_[ai][ei] = make_hrir_blob_at(az, el, sample_rate);
            }
        }
        built_ = true;
    }

    bool ready() const noexcept { return built_; }

    // Bilinear lookup. azimuth wraps; elevation clamps. Output is written
    // into `out_left` / `out_right` (kHrirTaps floats each) — caller-allocated
    // so no allocs on hot path. We additionally do a frequency-domain
    // crossfade: instead of straight-mixing the two flanking azimuth bins in
    // time, we form a per-frequency interpolation that preserves phase. This
    // costs one round-trip FFT, but the kHrirTaps=256 case is small enough
    // that the cost is negligible against per-block convolution.
    void lookup(f32 azimuth_rad, f32 elevation_rad, f32* out_left, f32* out_right) const noexcept {
        // Wrap azimuth to [-π, π].
        f32 az = azimuth_rad;
        while (az > math::kPi)
            az -= math::kTwoPi;
        while (az < -math::kPi)
            az += math::kTwoPi;
        // Map to bin space: bin 0 is at -π, bin (N) is at +π (wraps).
        const f32 az_bin_f = (az + math::kPi) * (static_cast<f32>(kHrirAzBins) / math::kTwoPi);
        u32 ai0 = static_cast<u32>(std::floor(az_bin_f)) % kHrirAzBins;
        u32 ai1 = (ai0 + 1u) % kHrirAzBins;
        const f32 az_t = az_bin_f - std::floor(az_bin_f);

        // Elevation: clamp & bilinear-interp between the two flanking samples.
        f32 el = std::clamp(elevation_rad, kHrirElevations[0], kHrirElevations[kHrirElBins - 1]);
        u32 ei0 = 0, ei1 = 0;
        f32 el_t = 0.0f;
        for (u32 i = 0; i < kHrirElBins - 1u; ++i) {
            if (el <= kHrirElevations[i + 1]) {
                ei0 = i;
                ei1 = i + 1u;
                el_t = (el - kHrirElevations[i]) / (kHrirElevations[i + 1] - kHrirElevations[i]);
                break;
            }
        }
        if (kHrirElBins == 1u) {
            ei0 = ei1 = 0;
            el_t = 0.0f;
        }

        // 1. elevation-blend each azimuth bin first (time-domain linear lerp).
        std::array<f32, kHrirTaps> ai0_left{}, ai0_right{};
        std::array<f32, kHrirTaps> ai1_left{}, ai1_right{};
        const HrirCell& c00 = cells_[ai0][ei0];
        const HrirCell& c01 = cells_[ai0][ei1];
        const HrirCell& c10 = cells_[ai1][ei0];
        const HrirCell& c11 = cells_[ai1][ei1];
        for (u32 i = 0; i < kHrirTaps; ++i) {
            ai0_left[i] = c00.left[i] * (1.0f - el_t) + c01.left[i] * el_t;
            ai0_right[i] = c00.right[i] * (1.0f - el_t) + c01.right[i] * el_t;
            ai1_left[i] = c10.left[i] * (1.0f - el_t) + c11.left[i] * el_t;
            ai1_right[i] = c10.right[i] * (1.0f - el_t) + c11.right[i] * el_t;
        }

        // 2. azimuth-blend: frequency-domain crossfade between bins. Cheap
        //    because kHrirTaps is a power of two (256 → log2n = 8). We
        //    do this per ear separately.
        freq_xfade(ai0_left.data(), ai1_left.data(), az_t, out_left);
        freq_xfade(ai0_right.data(), ai1_right.data(), az_t, out_right);
    }

    // Test hook — direct accessor for a single cell.
    const HrirCell& cell(u32 az_bin, u32 el_bin) const noexcept { return cells_[az_bin][el_bin]; }

    static constexpr u32 azimuth_bins() noexcept { return kHrirAzBins; }
    static constexpr u32 elevation_bins() noexcept { return kHrirElBins; }
    static constexpr u32 taps() noexcept { return kHrirTaps; }

   private:
    // Per-ear frequency-domain crossfade between two kHrirTaps-length signals.
    // log2(256) = 8. Operates in-place on scratch buffers reused per call —
    // not thread-local statics (per-call stack avoids cross-thread state).
    static void freq_xfade(const f32* a, const f32* b, f32 t, f32* out) noexcept {
        constexpr u32 N = kHrirTaps;
        constexpr u32 log2N = 8;
        f32 buf_a[2 * N]{};
        f32 buf_b[2 * N]{};
        for (u32 i = 0; i < N; ++i) {
            buf_a[2 * i + 0] = a[i];
            buf_a[2 * i + 1] = 0.0f;
            buf_b[2 * i + 0] = b[i];
            buf_b[2 * i + 1] = 0.0f;
        }
        fft(buf_a, log2N);
        fft(buf_b, log2N);
        // Per-bin: amplitude is linearly blended; phase is taken from
        // whichever flanking bin contributes more (so the result rotates
        // smoothly with t instead of cancelling at t = 0.5).
        for (u32 i = 0; i < N; ++i) {
            const f32 ar = buf_a[2 * i + 0], ai = buf_a[2 * i + 1];
            const f32 br = buf_b[2 * i + 0], bi = buf_b[2 * i + 1];
            const f32 mag_a = std::sqrt(ar * ar + ai * ai);
            const f32 mag_b = std::sqrt(br * br + bi * bi);
            const f32 mag = mag_a * (1.0f - t) + mag_b * t;
            // pick dominant-side phase
            f32 phr = 0.0f, phi = 0.0f;
            if (mag_a >= mag_b) {
                if (mag_a > 1e-12f) {
                    phr = ar / mag_a;
                    phi = ai / mag_a;
                }
            } else {
                if (mag_b > 1e-12f) {
                    phr = br / mag_b;
                    phi = bi / mag_b;
                }
            }
            buf_a[2 * i + 0] = mag * phr;
            buf_a[2 * i + 1] = mag * phi;
        }
        ifft(buf_a, log2N);
        for (u32 i = 0; i < N; ++i)
            out[i] = buf_a[2 * i + 0];
    }

    bool built_ = false;
    u32 sr_ = 48000;
    // [az][el] → cell. Linear (cache-friendly) for the AZ-major scan we do
    // in lookup().
    std::array<std::array<HrirCell, kHrirElBins>, kHrirAzBins> cells_{};
};

}  // namespace psynder::audio::detail
