// SPDX-License-Identifier: MIT
// Psynder — portal-graph traversal helpers. Lane 10 (world-bsp) owns.
//
// Wave A declared the portal data + API surface in Portal.h and shipped a
// PVS-only fallback for `walk_portal_visible_leaves`. Wave B (this header +
// PortalClip.cpp) lands the real frustum-clipping graph walk:
//
//   * `clip_frustum_by_portal` — clip a 4..6-plane frustum by the side
//     planes generated from the eye and each portal-polygon edge. If the
//     clipped frustum has zero area (any side plane rejects the entire
//     portal polygon), the portal contributes no visibility.
//
//   * `portal_visible_from_eye` — fast back-face/contained test. A portal
//     is visible from `eye` only if the eye lies on its front side AND the
//     portal polygon intersects the current frustum.
//
// The traversal in `walk_portal_visible_leaves` (defined in PortalClip.cpp)
// performs a BFS over portal-connected leaves: start from the eye's leaf,
// enqueue (leaf, frustum) pairs, and for each pair clip the frustum by every
// portal whose `front_leaf` is the current leaf, recursing into `back_leaf`
// with the clipped frustum. Each leaf is emitted at most once per walk —
// re-entrance through a different portal would be a strictly tighter frustum
// (or equal), but the renderer only needs to draw the leaf once per frame, so
// we drop duplicate visits.
//
// We keep the public API in Portal.h frozen — only `walk_portal_visible_leaves`
// changes behaviour. The internal helpers below are exposed here so the unit
// test can drive the clipping math directly without going through the BFS.

#pragma once

#include <vector>  // Portal.h pulls in Bsp.h which uses std::vector without <vector>.
#include "Portal.h"
#include "math/Math.h"

namespace psynder::world::bsp {

// Clip `in` (4..6 inward-pointing planes) against the side planes generated by
// extruding each edge of the portal polygon from `eye`. The portal polygon is
// the CCW winding of `portal` (indexing into `vertices`). On return, `out`
// holds the intersected frustum; the function returns `false` if the portal
// polygon falls entirely outside `in` (no visibility through this portal).
//
// The output plane count is at most kMaxFrustumPlanes; if the portal has more
// edges than fit, we keep the first kMaxFrustumPlanes - in.plane_count side
// planes (the dropped edges are conservatively visible — over-emit is correct,
// under-emit is the bug we never want).
bool clip_frustum_by_portal(const PortalFrustum& in,
                            const BspPortal& portal,
                            const std::vector<math::Vec3>& vertices,
                            math::Vec3 eye,
                            PortalFrustum& out);

// True if `eye` is on the front (PVS-visible) side of `portal`. CCW winding
// from `front_leaf` toward `back_leaf` means the polygon normal points
// front → back; the eye must lie on the front side to *enter* the portal.
bool portal_visible_from_eye(const BspPortal& portal, math::Vec3 eye);

// Test if a point is inside an inward-pointing frustum. (Inside = on or in
// front of every plane.) Exposed for tests.
bool point_in_frustum(const PortalFrustum& f, math::Vec3 p);

// kMaxFrustumPlanes (the clip plane cap) now lives in Portal.h next to
// PortalFrustum so the array size and the cap stay a single source of truth.

}  // namespace psynder::world::bsp
